description: Chart for InfluxDB
engine: gotpl
home: https://www.influxdata.com/time-series-platform/influxdb/
keywords:
- influxdb
- database
- timeseries
maintainers:
- email: jack@influxdb.com
  name: Jack Zampolin
name: influxdb
version: 0.1.0
