apiVersion: v1
description: A Minio Helm chart for Kubernetes
home: https://minio.io
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
name: minio
sources:
- https://github.com/minio/minio
version: 0.0.1
