apiVersion: v1
appVersion: 2.8.1
description: Elegantly enables a Tiller per namespace in RBAC-enabled clusters
maintainers:
- email: kent.rancourt@microsoft.com
  name: krancour
name: magic-namespace
version: 0.1.0
