apiVersion: v1
appVersion: 6.2.3
description: A Helm chart to collect Kubernetes logs with filebeat
icon: https://www.elastic.co/assets/blt47799dcdcf08438d/logo-elastic-beats-lt.svg
maintainers:
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: shane.starcher@gmail.com
  name: sstarcher
name: filebeat
sources:
- https://www.elastic.co/guide/en/beats/filebeat/current/index.html
version: 0.1.1
