description: Provide IAM credentials to containers running inside a kubernetes cluster
  based on annotations.
engine: gotpl
keywords:
- kube2iam
- aws
- iam
- security
maintainers:
- email: jm.carp@gmail.com
  name: Josh Carp
- email: michael.haselton@gmail.com
  name: Michael Haselton
name: kube2iam
sources:
- https://github.com/jtblin/kube2iam
version: 0.1.0
