apiVersion: v1
appVersion: 3.7.3
description: Highly available RabbitMQ cluster, the open source message broker software
  that implements the Advanced Message Queuing Protocol (AMQP).
home: https://www.rabbitmq.com
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
keywords:
- rabbitmq
- message queue
- AMQP
- MQTT
- STOMP
maintainers:
- email: etienne.tremel@container-solutions.com
  name: etiennetremel
name: rabbitmq-ha
sources:
- https://github.com/rabbitmq/rabbitmq
- https://github.com/docker-library/rabbitmq
version: 1.0.0
