appVersion: 6.5.26
deprecated: true
description: DEPRECATED SugarCRM enables businesses to create extraordinary customer
  relationships with the most innovative and affordable CRM solution in the market.
engine: gotpl
home: http://www.sugarcrm.com/
icon: https://bitnami.com/assets/stacks/sugarcrm/img/sugarcrm-stack-110x117.png
keywords:
- sugarcrm
- CRM
name: sugarcrm
sources:
- https://github.com/bitnami/bitnami-docker-sugarcrm
version: 1.0.7
