apiVersion: v1
appVersion: 0.4.2
description: Open source, tool for automating Kubernetes deployment updates. Keel
  is stateless, robust and lightweight.
engine: gotpl
home: https://keel.sh
keywords:
- kubernetes deployment
- helm release
- continuous deployment
maintainers:
- email: rmocius@gmail.com
  name: rimusz
- email: karolis.rusenas@gmail.com
  name: rusenask
name: keel
sources:
- https://github.com/rusenask/keel
version: 0.2.1
