description: Chart for Redis
engine: gotpl
home: http://redis.io/
keywords:
- redis
- keyvalue
- database
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: redis
sources:
- https://github.com/bitnami/bitnami-docker-redis
version: 0.4.3
