description: Chart for MongoDB
engine: gotpl
home: https://mongodb.org
keywords:
- mongodb
- database
- nosql
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: mongodb
sources:
- https://github.com/bitnami/bitnami-docker-mongodb
version: 0.4.4
