apiVersion: v1
description: A Helm chart for Kubernetes
home: http://spinnaker.io/
maintainers:
- email: viglesias@google.com
  name: Vic Iglesias
name: spinnaker
sources:
- https://github.com/spinnaker
- https://github.com/viglesiasce/images
version: 0.1.0
