description: Chart for selenium grid
engine: gotpl
home: http://www.seleniumhq.org/
icon: http://docs.seleniumhq.org/images/big-logo.png
keywords:
- qa
maintainers:
- email: techops@adaptly.com
  name: Philip Champon (flah00)
name: selenium
sources:
- https://github.com/SeleniumHQ/docker-selenium
version: 0.1.1
