apiVersion: v1
appVersion: RELEASE.2018-03-16T22-52-12Z
description: Distributed object storage server built for cloud applications and devops.
home: https://minio.io
icon: https://www.minio.io/img/logo_160x160.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: hello@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: 1.0.1
