description: CoreDNS is a DNS server that chains middleware and provides Kubernetes
  DNS Services
home: https://coredns.io
icon: https://raw.githubusercontent.com/coredns/logo/master/Icon/CoreDNS_Colour_Icon.svg
keywords:
- coredns
- dns
- kubedns
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: shashidhara.huawei@gmail.com
  name: Shashidhara TD
name: coredns
sources:
- https://github.com/coredns/coredns
version: 0.6.0
