description: Chart for PostgreSQL
engine: gotpl
home: https://www.postgresql.org/
keywords:
- postgresql
- postgres
- database
- sql
maintainers:
- name: swordbeta
- name: databus23
name: postgresql
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/postgres
version: 0.3.2
