apiVersion: v1
appVersion: 3.0.0
description: Voyager provides controller for Ingress and Certificates for Kubernetes
  developed by AppsCode.
icon: https://cdn.appscode.com/images/icon/voyager.png
maintainers:
- email: support@appscode.com
  name: appscode
name: voyager
sources:
- https://github.com/appscode/voyager
version: 1.0.0
