description: Highly available and distributed service discovery and key-value store
  designed with support for the modern data center to make distributed systems and
  configuration easy.
home: https://github.com/hashicorp/consul
icon: https://www.consul.io/assets/images/logo_large-475cebb0.png
maintainers:
- email: lachlan@deis.com
  name: Lachlan Evenson
name: consul
sources:
- https://github.com/kelseyhightower/consul-on-kubernetes
version: 0.2.2
