description: Sysdig Monitor Agent.
home: https://www.sysdig.com/
icon: https://app.sysdigcloud.com/images/changelogs/sysdig_monitor.png
keywords:
- monitoring
- alerting
- metric
- troubleshooting
maintainers:
- email: lachlan@deis.com
  name: Lachlan Evenson
- email: jorge.salamero@sysdig.com
  name: Jorge Salamero
name: sysdig
sources:
- https://app.sysdigcloud.com/#/settings/user
- https://github.com/draios/sysdig
version: 0.2.0
