description: GitLab Community Edition
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
maintainers:
- email: gtaylor@gc-taylor.com
  name: Greg Taylor
name: gitlab-ce
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce/
- https://docs.gitlab.com/omnibus/
version: 0.1.3
